apiVersion: apps/v1
kind: Deployment
metadata:
  name: perm-test-deployment
  namespace: perm-test
  labels:
    app: perm-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perm-test
  template:
    metadata:
      labels:
        app: perm-test
    spec:
      containers:
        - name: nginx
          image: registry.cluster.local/perm-test:1.0
          volumeMounts:
            - mountPath: /etc/watcher/tmp
              name: tmp
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 500Mi
      imagePullSecrets:
        - name: docker-registry-key
      securityContext:
        fsGroup: 10000
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
